options:
  registry_tag:
    type: string
    default: 2.6.0
    description: Registry tag to run
  registry_port:
    type: int
    default: 5000
    description: Host port to bind the Docker registry
  install_from_upstream:
    type: boolean
    default: true
    description: Force it to workaround Server/Client API mismatches
  swift_auth_url:
    type: string
    default: ""
    description: >
        A keystone auth url.
  swift_region_name:
    type: string
    default: ""
    description: >
        A keystone region name.
  swift_tenant_name:
    type: string
    default: ""
    description: >
        A keystone tenant name.
  swift_username:
    type: string
    default: ""
    description: >
        A keystone username.
  swift_password:
    type: string
    default: ""
    description: >
        A keystone password.
