version: "2"
services:
  registry:
    restart: always
    image: registry:{{ registry_tag }}
    ports:
      - "{{ registry_port }}:{{ registry_port }}"
    environment:
      # this dummy var is here just so parsing of the environment
      # section is okay even without any conditionsl being true
      DUMMY: dummy
    {% if registry_cert and registry_key %}
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/docker-registry.crt
      REGISTRY_HTTP_TLS_KEY: /keys/docker-registry.key
    {% if registry_htpasswd %}
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /configs/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    {% endif %}
    volumes:
      - /etc/ssl/certs/:/certs
      - /etc/ssl/private/:/keys
      - /usr/local/etc/:/configs
    {% endif %}
